# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := cluster pattern

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

cluster: pattern
	@echo "==== Building cluster ($(config)) ===="
	@${MAKE} --no-print-directory -C example -f Makefile

pattern: 
	@echo "==== Building pattern ($(config)) ===="
	@${MAKE} --no-print-directory -C src -f Makefile

clean:
	@${MAKE} --no-print-directory -C example -f Makefile clean
	@${MAKE} --no-print-directory -C src -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo "   debug32"
	@echo "   release32"
	@echo "   debug64"
	@echo "   release64"
	@echo "   debuguniv"
	@echo "   releaseuniv"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   cluster"
	@echo "   pattern"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
